const Fields = {
  day: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
  gender: ["Male", "Female"],
  tution_type: ["Online", "Offline"],
  medium: ["Bangla Medium", "English Medium", "English Version"],
  subject: [
    "Bangla",
    "English",
    "Math",
    "Physics",
    "Chemistry",
    "Biology",
    "ICT",
    "Science",
  ],
  days_per_week: [1, 2, 3, 4, 5, 6, 7],
  class: [
    "Class 1",
    "Class 2",
    "Class 3",
    "Class 4",
    "Class 5",
    "Class 6",
    "Class 7",
    "Class 8",
    "Class 9",
    "Class 10",
    "Class 11",
    "Class 12",
    "HSC",
    "SSC",
    "A Level",
    "O Level",
    "Engineering Admission",
    "Medical Admission",
    "Versity Admission",
  ],
};

export default Fields;
